Comment.create!([
  {user_id: 2, topic_id: 2, post_id: 1, content: "Thanks for the useful tips!", votes: nil, comment_id: nil},
  {user_id: 1, topic_id: 2, post_id: 1, content: "Glad you found that helpful ;)", votes: nil, comment_id: 1},
  {user_id: 1, topic_id: 3, post_id: 2, content: "Doesn't seem very accurate as wikipedia reports the top speed to be 431 km/h (268 mph)... or perhaps wiki reported incorrect information? Here is an excerpt from wikipedia at:\r\n\r\nhttps://en.wikipedia.org/wiki/List_of_fastest_production_cars\r\n\r\n[...] Comparing claimed speeds of the \"fastest car(s) in the world\", especially in historical cases, is difficult as there is no standardized method for determining the top speed, nor a central authority to verify any such claims. The current title Guinness World Records holder, the Bugatti Veyron Super Sport, was certified for the average top speed achieved on a two-way run, registering 431 km/h (268 mph). While only 5 of the World Record model were made out of a total of 30 Super Sports, the other 25 Super Sports will all also achieve this speed with the limiter turned off. Guinness, after a review by a panel of experts, consider this not to be a modification and thus it is eligible for this list.\r\n\r\nIn 2014, a Hennessey Venom GT was recorded as exceeding 270.49 mph (435.31 km/h), but as the run was in one direction only, and only 16 cars out of a planned total of 29 have been sold, it does not qualify under the Guinness Book of Records or this list's criteria as the world's fastest production car. [...]\r\n", votes: nil, comment_id: nil},
  {user_id: 1, topic_id: 6, post_id: 7, content: "Dr. Strangelove: Of course, the whole point of a Doomsday Machine is lost, if you *keep* it a *secret*! Why didn't you tell the world, EH?\r\nAmbassador de Sadesky: It was to be announced at the Party Congress on Monday. As you know, the Premier loves surprises. ", votes: nil, comment_id: nil},
  {user_id: 3, topic_id: 6, post_id: 7, content: "Gentlemen, you can't fight in here! This is the War Room. ;)", votes: nil, comment_id: 4},
  {user_id: 3, topic_id: 3, post_id: 2, content: "Well... this wiki article might clarify things: The current Super Sport version of the Veyron is recognised by Guinness World Records as the fastest street-legal production car in the world, with a top speed of 430.9 km/h (267.7 mph),[5] and the roadster Veyron Grand Sport Vitesse version is the fastest roadster in the world, reaching an averaged top speed of 408.84 km/h (254.04 mph) in a test on 6 April 2013.\r\nSo different production version reached slightly different speeds with the Super Sport model being the current record holder (By the way the Hennessy Venom GT didn't make the cut due to not enough units sold).", votes: nil, comment_id: 3}
])
Post.create!([
  {user_id: 1, topic_id: 3, content: "The Lamborghini Aventador is a mid-engined sports car produced by the Italian manufacturer Lamborghini.\r\n\r\nLaunched on 28 February 2011 at the Geneva Motor Show, five months after its initial unveiling in Sant'Agata Bolognese, the vehicle, internally codenamed LB834, was designed to replace the ten-year-old Murciélago as the new flagship model.", votes: 1},
  {user_id: 1, topic_id: 3, content: "Super Sportcars: Bugatti Veyron. 408.84 km/h\r\nA Bugatti Veyron 16.4 Grand Sport Vitesse driven by the Chinese racing driver Anthony Liu at Volkswagen Group's proving grounds in Ehra-Lessien became the fastest open-top production sports car, with speed of 408.84 km/h (254.04 mph).", votes: 1},
  {user_id: 1, topic_id: 4, content: "Cannonau di Sardegna \r\nD.O.C. Riserva\r\n\r\nBright ruby color, with purple hues, the aromas project ripe red berry, including strawberry and raspberry jam. In the mouth, coffee, spices and herbs, including an aroma of violets, plummy fruit flavours and aristocratic oak overtone. Full, round, fruit forward, consumer friendly taste profile. Oak aged for two years in large Slavonian casks with several additional months in the bottle. Medium-bodied for food-friendly matchings.", votes: 0},
  {user_id: 2, topic_id: 6, content: "The Time Travelers, by Ib Melchior (1964, 82 min, 35mm)\r\nStep through “The Time Portal” beyond the crack in Space and Time where the fantastic world of the Future will freeze your blood with its weird horrors!", votes: 0},
  {user_id: 1, topic_id: 2, content: "Safe riding tips: T-CLOCS always/often before riding; Gear up for riding distance and weather conditions; Never ride tired.", votes: 0},
  {user_id: 1, topic_id: 6, content: "One of the greatest films of all times: Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb, more commonly known as Dr. Strangelove, is a 1964 political satire black comedy film that satirizes the Cold War fears of a nuclear conflict between the USSR and the US. The film was directed, produced, and co-written by Stanley Kubrick, stars Peter Sellers and George C. Scott, and features Sterling Hayden, Keenan Wynn, and Slim Pickens. Production took place in the United Kingdom. The film is loosely based on Peter George's thriller novel Red Alert.", votes: 0}
])
Topic.create!([
  {title: "Motorbikes", user_id: 1, archived: false, votes: 0},
  {title: "Cars", user_id: 1, archived: false, votes: 0},
  {title: "Wines", user_id: 1, archived: false, votes: 0},
  {title: "Music", user_id: 2, archived: nil, votes: 0},
  {title: "Movies", user_id: 2, archived: nil, votes: 0}
])
User.create!([
  {first_name: "Toti", last_name: "Fanara", email: "toti.fanara@gmail.com", password_digest: "$2a$10$BhN5Yy9wPxK9HB4d/dU5lugQPzq77OWylevoeU3HXdtuTowL0L.jK", votes: nil, is_admin: false, is_moderator: false, active: true, last_login: "2015-09-17 15:56:00", last_logout: "2015-09-17 15:56:00"},
  {first_name: "John", last_name: "Doe", email: "jdoe123@mailinator.com", password_digest: "$2a$10$BhN5Yy9wPxK9HB4d/dU5lugQPzq77OWylevoeU3HXdtuTowL0L.jK", votes: nil, is_admin: false, is_moderator: false, active: true, last_login: "2015-09-17 15:57:00", last_logout: "2015-09-17 15:57:00"},
  {first_name: "Jane", last_name: "Doe", email: "janedoe123@mailinator.com", password_digest: "$2a$10$GFgv597R/Nt1YxFer7vhPuCTYEKWeZ4lKfFxcDuFgrKocevE1BSva", votes: nil, is_admin: nil, is_moderator: nil, active: nil, last_login: nil, last_logout: nil}
])
